//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anthony_Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BottomType
    {
        public BottomType()
        {
            this.MyBottoms = new HashSet<MyBottom>();
        }
    
        public int BottomID { get; set; }
        public string BottomType1 { get; set; }
    
        public virtual ICollection<MyBottom> MyBottoms { get; set; }
    }
}
