//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anthony_Wardrobe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClothingDatabaseEntities : DbContext
    {
        public ClothingDatabaseEntities()
            : base("name=ClothingDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessoryType> AccessoryTypes { get; set; }
        public DbSet<BottomType> BottomTypes { get; set; }
        public DbSet<MyAccessory> MyAccessories { get; set; }
        public DbSet<MyBottom> MyBottoms { get; set; }
        public DbSet<MySho> MyShoes { get; set; }
        public DbSet<MyTop> MyTops { get; set; }
        public DbSet<ShoeType> ShoeTypes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TopType> TopTypes { get; set; }
    }
}
