//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anthony_Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MyAccessory
    {
        public int MyAccessoryID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public int AccessoryID { get; set; }
        public string Color { get; set; }
        public string Season { get; set; }
        public string Occasion { get; set; }
    
        public virtual AccessoryType AccessoryType { get; set; }
    }
}
