//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anthony_Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopType
    {
        public TopType()
        {
            this.MyTops = new HashSet<MyTop>();
        }
    
        public int TopID { get; set; }
        public string TopType1 { get; set; }
    
        public virtual ICollection<MyTop> MyTops { get; set; }
    }
}
